name: Scorecard Clock System

env:
  DISPLAY: ":99.0"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
     xvfb:
      image: selenium/standalone-chrome:latest
      options: -e VNC_SERVER=true -e VNC_PORT=5900

    steps:
    - uses: actions/checkout@v4

    - name: "Run analysis"
      uses: ossf/scorecard-action@0864cf19026789058feabb7e87baa5f140aac736
      with:
        results_file: results.sarif
        results_format: sarif
        publish_results: true

      # Upload the results as artifacts (optional). Commenting out will disable uploads of run results in SARIF
      # format to the repository Actions tab.
    - name: "Upload artifact"
      uses: actions/upload-artifact@v4 
      with:
        name: SARIF file
        path: results.sarif
        retention-days: 5
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"
    
    - name: Build with Gradle
      run: gradle build
