name: Scorecard Clock System

env:
  DISPLAY: ":99.0"

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ "*" ]

jobs:
  build:

    runs-on: ubuntu-latest
    permissions:
      contents: read

    services:
     xvfb:
      image: selenium/standalone-chrome:latest
      options: -e VNC_SERVER=true -e VNC_PORT=5900

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Start Xvfb
      run: Xvfb $DISPLAY -ac -screen 0 1600x1200x24 > /dev/null 2>&1 &

    # Configure Gradle for optimal use in GitHub Actions, including caching of downloaded dependencies.
    # See: https://github.com/gradle/actions/blob/main/setup-gradle/README.md
    - name: Setup Gradle 8.10
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: "8.10"
    
    - name: Build with Gradle
      run: gradle build
